check_every: 60
activation_threshold: 200
producers:
    - id: 0
      name: 'Solarpanel 1'
      type: 'constant'
      config:
        value: '2360.2'
    - id: 1
      name: 'Solarpanel 2'
      type: 'constant'
      config:
        value: '0.3'

consumers:
    - id: 0
      name: 'Fake 1'
      type: 'fakeControllable'
      config:
        value: '111'
        status: 'READY'
    - id: 1
      name: 'Tesla Ladestation'
      type: 'constant'
      config:
        value: '1433.16'
    - id: 2
      name: 'Aussenlicht'
      type: 'constant'
      config:
        value: '0.0'

storages:
    - id: 0
      name: "My fake battery"
      type: 'constant'
      config:
        value: '98'
