producers:
    - id: 0
      name: 'Solarpanel 1'
      type: 'constant'
      config:
        value: '236.2'
    - id: 1
      name: 'Solarpanel 2'
      type: 'constant'
      config:
        value: '0.3'

consumers:
    - id: 0
      name: 'Waschmachine'
      type: 'constant'
      config:
        value: '111'
    - id: 1
      name: 'Tesla Ladestation'
      type: 'constant'
      config:
        value: '5433.16'
    - id: 2
      name: 'Aussenlicht'
      type: 'constant'
      config:
        value: '0.0'
